# This file was generated by JuDoc, do not modify it. # hide
using RDatasets, MLJ
MLJ.color_off() # hide , disable colors as they fail on web output
iris = dataset("datasets", "iris")

first(iris, 3) |> pretty
