# This file was generated by JuDoc, do not modify it. # hide
using MLJ, MLJBase, PrettyPrinting, DataFrames, Statistics
MLJ.color_off() # hide / @reader: feel free to comment this out

X, y = @load_reduced_ames
@show size(X)
first(X, 3) |> pretty
